// ==============================================================================
// IMPORTANT: DO NOT EDIT THIS FILE DIRECTLY
// ==============================================================================
// This file is managed from a central 'easi6dev/tada-server-common-source' repository.
// Any changes made here will be overwritten the next time the sync workflow runs.
// ==============================================================================

tasks.register("setupGitHooks") {
    description = "Configure git to use .github/hooks as the hooks directory"
    group = "setup"

    val gitDir = file(".git")
    val expectedPath = ".github/hooks"

    onlyIf {
        if (!gitDir.exists() || !gitDir.isDirectory) return@onlyIf false
        val result = providers.exec {
            commandLine("git", "config", "core.hooksPath")
            isIgnoreExitValue = true
        }
        result.standardOutput.asText.get().trim() != expectedPath
    }

    doLast {
        exec {
            commandLine("git", "config", "core.hooksPath", ".github/hooks")
        }
        println("Git hooks path set to .github/hooks")
    }
}
