name: Valhalla MinGW Build
on:
  pull_request:
    branches:
      - _disabled

jobs:
  build:
    name: MinGW64 build
    runs-on: ubuntu-latest
    container: fedora:rawhide
    steps:
      - name: Get dependencies
        run: |
          dnf install -y \
            cmake \
            gcc-c++ \
            git \
            make \
            mingw64-gcc \
            mingw64-gcc-c++ \
            mingw64-curl \
            mingw64-boost \
            mingw64-protobuf \
            mingw64-geos \
            mingw64-gdal \
            mingw64-python3 \
            lz4-devel \
            protobuf-compiler
      - name: Build lz4 for MinGW
        run: |
          LZ4_VERSION=1.9.4
          curl -sL https://github.com/lz4/lz4/archive/refs/tags/v${LZ4_VERSION}.tar.gz | tar xz
          cd lz4-${LZ4_VERSION}
          mingw64-make -j$(nproc) \
            CC=x86_64-w64-mingw32-gcc \
            AR=x86_64-w64-mingw32-ar \
            PREFIX=/usr/x86_64-w64-mingw32/sys-root/mingw \
            install
          cd ..
          rm -rf lz4-${LZ4_VERSION}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Configure and run build
        run: |
          mkdir build && cd build \
          && mingw64-cmake .. \
            -DCMAKE_CROSS_COMPILING=1 \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_TOOLS=OFF \
            -DENABLE_DATA_TOOLS=OFF \
            -DENABLE_SERVICES=OFF \
            -DENABLE_PYTHON_BINDINGS=ON \
            -DENABLE_CCACHE=OFF \
            -DENABLE_TESTS=OFF \
            -DLOGGING_LEVEL=DEBUG \
            -DBoost_PROGRAM_OPTIONS_LIBRARY=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/libboost_program_options-mt-x64.dll.a \
            -DPYTHON_EXECUTABLE=/usr/x86_64-w64-mingw32/bin/python3 \
            -DPYTHON_LIBRARIES=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpython3.9.dll.a \
            -DPYTHON_INCLUDE_DIRS=/usr/x86_64-w64-mingw32/sys-root/mingw/include/python3.9 \
          && mingw64-make -j$(nproc)
